## NOTE: This has not been verified yet

image: 
  name: ghcr.io/bossm8/portfoli-go:latest
  entrypoint: /bin/sh

variables:
  CONF_DIR: ./configs
  DIST_DIR: ./public
  CUSTOM_CONTENT_DIR: ./custom
  # https://docs.gitlab.com/ee/user/project/pages/getting_started_part_one.html#gitlab-pages-default-domain-names
  # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  SRV_BASE_PATH: /${CI_PROJECT_NAME}

pages:
  stage: deploy
  script:
    - mkdir ${DIST_DIR}
    - portfoli-go-static.sh
    - cp -r ${CUSTOM_CONTENT_DIR} ${DIST_DIR}/static/img/custom
  artifacts:
    paths:
      - public
  only:
    refs:
      - main