image: 
  name: ghcr.io/bossm8/portfoli-go:latest
  entrypoint: /bin/sh

variables:
  CONFIGS_DIR: ./configs
  CUSTOM_CONTENT_DIR: ./custom
  # https://docs.gitlab.com/ee/user/project/pages/getting_started_part_one.html#gitlab-pages-default-domain-names
  # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  BASE_PATH: /${CI_PROJECT_NAME}

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r /var/www/portfoli.go/public public/static
    - cp -r ${CUSTOM_CONTENT_DIR} public/static/img/custom
    - mv public/static/favicon.ico public
    - portfoli-go -config.dir ${CONFIGS_DIR} -dist -dist.dir ${PWD}/public -srv.base ${BASE_PATH}
  artifacts:
    paths:
      - public
  only:
    refs:
      - main