services:

  portfoli.go:
    image: gchr.io/bossm8/portfoli-go:latest
    container_name: portfoli.go
    volumes:
      - ${PWD}/configs:/var/www/portfoli.go/configs:ro
      - ${PWD}/content:/var/www/portfoli.go/public/img/custom:ro
    ports:
      - "127.0.0.1:8080:8080"