## NOTE: This has not been verified yet

name: Build Pages

on:
  push:
    branches:
      - "main"
    
jobs:
  build-pages:
    runs-on: ubuntu-latest
    environment:
      MOUNT_DIR: /var/www/portfoli.go/workspace/configs
      CONF_DIR: configs
      DIST_DIR: public
      CUSTOM_CONTENT_DIR: custom
      SRV_BASE_PATH: /${{ github.event.repository.name }}

    steps:

      - name: Checkout Configs
        uses: actions/checkout@v3

      - name: Build Pages
        uses: addnab/docker-run-action@v3
        with: 
          image: ghcr.io/bossm8/portfoli-go:latest
          options: -v ${{ github.workspace }}:${{ MOUNT_DIR }} --entrypoint /bin/sh
          run: |
            mkdir ${{ MOUNT_DIR }}/${{ DIST_DIR }}
            portfoli-go-static.sh
            cp -r ${{ MOUNT_DIR }}/${{ CUSTOM_CONTENT_DIR }} ${{ MOUNT_DIR }}/${{ DIST_DIR }}/static/img/custom
      
      - name: Build Artifact
        uses: actions/upload-pages-artifact
        with:
          path: ${{ github.workspace }}/${{ DIST_DIR }}

  deploy:
    needs: build-pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1