# Your projects
projects:
    # Name of the project
  - name: Gopher Artwork
    # Link to e.g. the website of your project
    link: https://github.com/bossm8/portfoli.go/tree/main/static/img
    # Optional image (either url or path starting from /static)
    image: /static/img/portfoli.go-gray.svg
    # A description of the project, this may be HTML content
    description: |
      <div>
        <img class="img-fluid" src='{{ "/static/img/status/404.svg" | Assemble }}' alt="Much Wow"/><br/>
        <img class="img-fluid" src='{{ "/static/img/status/error.svg" | Assemble }}' alt="Hmm - cannot find this"/><br/>
        <img class="img-fluid" src='{{ "/static/img/status/delivered.svg" | Assemble }}' alt="Might be missing too"/><br/>
        <img class="img-fluid" src='{{ "/static/img/status/undelivered.svg" | Assemble }}' alt="No idea what else I could write here"/><br/>
      </div>

  - name: Portfoli.go
    link: /about
    description: |
      <div class="mb-3">
        <strong>The simple and flexible portfolio written in Go and Bootstrap.</strong>
      </div>
      <div class="mt-3">
        There could be written a lot about it.
        However most information is written in the source code repository on GitHub:
      </div>
      <div class="mt-4">
        <a href="https://github.com/bossm8/portfoli.go" target="_blank" class="btn btn-primary">
          <i class="bi bi-github me-2"></i>Source Code
        </a>
      </div>
