name: Build Latest Tag

on:
  schedule:
    - cron: "00 01 * * 0"

  push:
    branches:
      - 'main'

  workflow_run:
    workflows:
      - 'Run Tests'
    branches:
      - 'main'
    types:
      - 'completed'
      

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/portfoli-go

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' }}
    permissions:
      contents: read
      packages: write    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: docker/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
