name: Build Pages

on:
  workflow_run:
    workflows:
      - Build Latest Tag
    types:
      - completed
      
  push:
    branches:
      - "main"
    #paths:
    #  - '**/*.go'
    #  - '**/*.sh'
    #  - 'public/**/*'
    #  - '.github/workflows/pages.yaml'
    #  - 'go.*'

env:
  MOUNT_DIR: /var/www/portfoli.go/workspace
  CONF_DIR: examples/configs
  DIST_DIR: public
    
jobs:
  build-pages:
    runs-on: ubuntu-latest
    environment:

    steps:

      - name: Checkout Configs
        uses: actions/checkout@v3

      - name: Build Pages
        uses: addnab/docker-run-action@v3
        with: 
          image: ghcr.io/bossm8/portfoli-go:latest
          options: -v ${{ github.workspace }}:${{ env.MOUNT_DIR }} --entrypoint /bin/sh -e DIST_PATH=${{ env.MOUNT_DIR }}/${{ env.DIST_DIR }} -e CONF_PATH=${{ env.MOUNT_DIR }}/${{ env.CONF_DIR }}
          run: |
            mkdir ${{ env.DIST_PATH }}
            portfoli-go-static.sh
      
      - name: Build Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ github.workspace }}/${{ env.DIST_DIR }}

  deploy:
    needs: build-pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1