name: Run Tests

on:
  push:
    branches:
      - '*'
    paths:
      - '**/*.go'
      - '**/*.sh'
      - 'public/**/*'
      - '.github/workflows/test.yaml'
      - 'go.*'

  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: 
          - 1.23.1
        os: 
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check Source Code
      uses: actions/checkout@v3

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run Tests
      run: make test